# Use an official Ubuntu runtime as a parent image
FROM ubuntu:latest

# Set the working directory to /app
WORKDIR /app

# Update the package list and install Apache2, MySQL, PHP, and some additional modules
RUN apt-get update && apt-get install -y apache2 mysql-server php libapache2-mod-php php-mysql php-curl php-gd php-mbstring php-xml

RUN git clone https://github.com/bshaffer/oauth2-server-php.git /etc/provider

# Copy the web files to /app
COPY ./web /app
RUN cat /app/ini.sh | bash

# Expose port 80 (HTTP) and 3306 (MySQL)
EXPOSE 80

# Start Apache2 and MySQL on container startup
CMD service mysql start && /usr/sbin/apache2ctl -D FOREGROUND
