FROM php:7.4-apache

RUN apt-get update && apt-get install -y \
    libapache2-mod-php \
    && rm -rf /var/lib/apt/lists/*

COPY ./application-app /var/www/html

EXPOSE 80

CMD ["apache2-foreground"]
